### ISSUE TITLE
Build should not bundle dependencies

### ISSUE THREAD

**Issue by marceljuenemann** [gjuchault/typescript-library-starter#344]
Thanks for this useful starter template!

One issue I ran into is that this setup is bundling *all* dependencies and dependencies of dependencies into the build, so the build output was tens of thousands of lines in my case. I think what you want is to bundle only the files that are part of the project, and rely on the package manager to pull in all dependencies listed in the package.json.

I didn't see a quick way to do that with esbuild, so in my project I just set bundle to false in the build.ts and added additional entry points for the files of my project

**Comment by marceljuenemann** [comment]
Seems this is a regression added in #113

**Comment by gjuchault** [comment]
Hello,

Initially, I was going to say that the whole point of esbuild & bundling in general is actually to have everything bundled, _including_ dependencies. This makes perfect sense for services that are to be deployed in an environment when installing packages is painful (typically if you have CI or Docker images, etc.)
Nonetheless, this is indeed weird for a library, since the goal is to be used by another package (that might be deployed itself).

I'll change this and keep bundling for the [typescript-service-starter](https://github.com/gjuchault/typescript-service-starter/) template

Edit: actually this has been fixed here: https://github.com/gjuchault/typescript-library-starter/pull/353
